version: '3.8'

networks:
  net_ab:
    name: net_ab
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.254
  net_bc:
    name: net_bc
    ipam:
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.254
  net_ac:
    name: net_ac
    ipam:
      config:
        - subnet: 10.0.3.0/24
          gateway: 10.0.3.254

services:
  router_a:
    build: .
    image: my-router
    container_name: router_a
    privileged: true
    environment:
      - ROUTER_ID=router_a
      - MY_IP=10.0.1.1
      - LOCAL_SUBNETS=10.0.1.0/24,10.0.3.0/24
      - NEIGHBORS=10.0.1.2,10.0.3.2
    networks:
      net_ab:
        ipv4_address: 10.0.1.1
      net_ac:
        ipv4_address: 10.0.3.1

  router_b:
    build: .
    image: my-router
    container_name: router_b
    privileged: true
    environment:
      - ROUTER_ID=router_b
      - MY_IP=10.0.1.2
      - LOCAL_SUBNETS=10.0.1.0/24,10.0.2.0/24
      - NEIGHBORS=10.0.1.1,10.0.2.2
    networks:
      net_ab:
        ipv4_address: 10.0.1.2
      net_bc:
        ipv4_address: 10.0.2.1

  router_c:
    build: .
    image: my-router
    container_name: router_c
    privileged: true
    environment:
      - ROUTER_ID=router_c
      - MY_IP=10.0.2.2
      - LOCAL_SUBNETS=10.0.2.0/24,10.0.3.0/24
      - NEIGHBORS=10.0.2.1,10.0.3.1
    networks:
      net_bc:
        ipv4_address: 10.0.2.2
      net_ac:
        ipv4_address: 10.0.3.2
